"""
Шаг 6: генератор советника MQL5 под конкретную ONNX-модель.

Берёт *.meta.json из выгрузки ONNX (список признаков, длина окна, горизонт) и пишет
файл эксперта: признаки считаются в MQL5, вероятность берётся из модели через OnnxRun,
вход по порогу, выход через N баров, защита спредом.

Нормировка вшита в ONNX-граф, поэтому советник подаёт сырые признаки.

Запуск:
    D:\\mql5-ml\\venv\\Scripts\\python.exe D:\\mql5-ml\\scripts\\14_make_ea.py
"""
import glob
import json
import os

MODELS_ONNX = r"D:\mql5-ml\models\onnx"
MT5 = r"D:\MetaTrader 5"
EXPERTS = os.path.join(MT5, "MQL5", "Experts", "HermesONNX")
os.makedirs(EXPERTS, exist_ok=True)

# как каждый признак считается в MQL5 (i - индекс бара в окне, 0 = самый старый)
EXPR = {
    "ret1": "ret1[i]",
    "ret3": "MathLog(c[i]/c[i-3])",
    "ret12": "MathLog(c[i]/c[i-12])",
    "vol20": "SampleStd(ret1,i-19,20)",
    "vol100": "SampleStd(ret1,i-99,100)",
    "vol_ratio": "(SampleStd(ret1,i-99,100)>1e-12 ? SampleStd(ret1,i-19,20)/SampleStd(ret1,i-99,100) : 0.0)",
    "atr14": "MeanOf(tr,i-13,14)/c[i]",
    "rsi14": "rsiArr[i]/100.0",
    "ma20_dist": "SmaDist(c,i,20)",
    "ma50_dist": "SmaDist(c,i,50)",
    "ma200_dist": "SmaDist(c,i,200)",
    "bb_pos": "BbPos(c,i)",
    "body": "((h[i]-l[i])>1e-12 ? (c[i]-o[i])/(h[i]-l[i]) : 0.0)",
    "upper_wick": "((h[i]-l[i])>1e-12 ? (h[i]-MathMax(c[i],o[i]))/(h[i]-l[i]) : 0.0)",
    "lower_wick": "((h[i]-l[i])>1e-12 ? (MathMin(c[i],o[i])-l[i])/(h[i]-l[i]) : 0.0)",
    "range_rel": "(h[i]-l[i])/c[i]",
    "vol_z": "VolZ(v,i)",
    "spread_pts": "spreadNow",
    "hour_sin": "MathSin(2*M_PI*((int)(((long)t[i]%86400)/3600))/24.0)",
    "hour_cos": "MathCos(2*M_PI*((int)(((long)t[i]%86400)/3600))/24.0)",
    "dow_sin": "MathSin(2*M_PI*((int)((((long)(t[i]/86400))+3)%7))/5.0)",
    "dow_cos": "MathCos(2*M_PI*((int)((((long)(t[i]/86400))+3)%7))/5.0)",
}

TEMPLATE = r'''//+------------------------------------------------------------------+
//|  @@NAME@@                                                       |
//|  Features are computed in MQL5, the model runs through ONNX.      |
//|  Generated by 14_make_ea.py  (Python -> ONNX -> MT5 pipeline)     |
//+------------------------------------------------------------------+
#property version   "1.00"
#property description "ONNX model: @@MODEL@@"
#property description "Sequence length @@SEQ@@ bars, prediction horizon @@HORIZON@@ bars"

#include <Trade\Trade.mqh>

input string InpOnnxFile   = "@@MODEL@@.onnx";  // model file in MQL5\Files
input bool   InpCommonFolder = true;            // load the model from the shared Common\Files folder (needed in the tester)
input double InpThreshold  = 0.55;              // enter when prob >= Thr (sell when prob <= 1-Thr)
input double InpLot        = 0.10;              // fixed lot
input int    InpSLPoints   = 0;                 // stop loss in points (0 = off)
input int    InpTPPoints   = 0;                 // take profit in points (0 = off)
input int    InpMaxSpread  = 40;                // skip bar when spread is wider (points)
input int    InpHoldBars   = @@HORIZON@@;       // exit after this many bars
input long   InpMagic      = @@MAGIC@@;         // magic number
input bool   InpVerbose    = true;              // print predictions to the log

#define SEQ        @@SEQ@@                      // bars fed into the model
#define NFEAT      @@NFEAT@@                    // number of features
#define WARMUP     320                          // extra bars for indicator warm-up
#define NEED       (SEQ + WARMUP)

long   g_onnx      = INVALID_HANDLE;
CTrade g_trade;
datetime g_lastBar   = 0;
datetime g_entryBar  = 0;
ulong    g_preds     = 0;
ulong    g_bought    = 0, g_sold = 0;

//+------------------------------------------------------------------+
//| helpers                                                          |
//+------------------------------------------------------------------+
double MeanOf(const double &a[], const int from, const int cnt)
  {
   if(from < 0 || cnt <= 0 || from + cnt > ArraySize(a))
      return(0.0);
   double s = 0.0;
   for(int k = from; k < from + cnt; k++)
      s += a[k];
   return(s / cnt);
  }

double SampleStd(const double &a[], const int from, const int cnt)
  {
   if(from < 0 || cnt < 2 || from + cnt > ArraySize(a))
      return(0.0);
   double m = MeanOf(a, from, cnt);
   double s = 0.0;
   for(int k = from; k < from + cnt; k++)
      s += (a[k] - m) * (a[k] - m);
   return(MathSqrt(s / (cnt - 1)));            // ddof = 1, as in pandas
  }

double SmaDist(const double &c[], const int i, const int period)
  {
   double m = MeanOf(c, i - period + 1, period);
   if(MathAbs(m) < 1e-12)
      return(0.0);
   return((c[i] - m) / m);
  }

double BbPos(const double &c[], const int i)
  {
   double m = MeanOf(c, i - 19, 20);
   double sd = SampleStd(c, i - 19, 20);
   if(sd < 1e-12)
      return(0.0);
   return((c[i] - m) / (2.0 * sd));
  }

double VolZ(const double &v[], const int i)
  {
   double m = MeanOf(v, i - 49, 50);
   double sd = SampleStd(v, i - 49, 50);
   if(sd < 1e-12)
      return(0.0);
   return((v[i] - m) / sd);
  }

bool HasPosition()
  {
   if(!PositionSelect(_Symbol))
      return(false);
   return(PositionGetInteger(POSITION_MAGIC) == InpMagic);
  }

void ClosePosition(const string why)
  {
   if(!HasPosition())
      return;
   if(!g_trade.PositionClose(_Symbol))
      Print("PositionClose failed: ", g_trade.ResultRetcode(), " ", g_trade.ResultComment());
   else if(InpVerbose)
      Print("closed (", why, ")");
   g_entryBar = 0;
  }

//+------------------------------------------------------------------+
//| build the feature matrix for the last closed bars                |
//+------------------------------------------------------------------+
bool BuildFeatures(matrixf &m, double &prob)
  {
   MqlRates r[];
   int copied = CopyRates(_Symbol, PERIOD_CURRENT, 1, NEED, r);   // start at shift 1: last closed bar
   if(copied < NEED)
     {
      Print("CopyRates returned ", copied, " of ", NEED, " bars");
      return(false);
     }

   int n = copied;
   double c[], h[], l[], o[], v[], t[];
   ArrayResize(c, n); ArrayResize(h, n); ArrayResize(l, n);
   ArrayResize(o, n); ArrayResize(v, n); ArrayResize(t, n);
   for(int k = 0; k < n; k++)
     {
      c[k] = r[k].close;  h[k] = r[k].high;  l[k] = r[k].low;
      o[k] = r[k].open;   v[k] = (double)r[k].tick_volume; t[k] = (double)r[k].time;
     }

//--- log returns
   double ret1[];
   ArrayResize(ret1, n);
   ret1[0] = 0.0;
   for(int k = 1; k < n; k++)
      ret1[k] = (c[k-1] > 0.0 && c[k] > 0.0) ? MathLog(c[k] / c[k-1]) : 0.0;

//--- true range
   double tr[];
   ArrayResize(tr, n);
   tr[0] = h[0] - l[0];
   for(int k = 1; k < n; k++)
     {
      double a = h[k] - l[k];
      double b = MathAbs(h[k] - c[k-1]);
      double d = MathAbs(l[k] - c[k-1]);
      tr[k] = MathMax(a, MathMax(b, d));
     }

//--- Wilder-style RSI (alpha = 1/14), same as pandas ewm
   double rsiArr[], up[], dn[];
   ArrayResize(rsiArr, n); ArrayResize(up, n); ArrayResize(dn, n);
   double alpha = 1.0 / 14.0;
   up[0] = 0.0; dn[0] = 0.0; rsiArr[0] = 50.0;
   for(int k = 1; k < n; k++)
     {
      double d = c[k] - c[k-1];
      double u = (d > 0.0) ? d : 0.0;
      double w = (d < 0.0) ? -d : 0.0;
      up[k] = alpha * u + (1.0 - alpha) * up[k-1];
      dn[k] = alpha * w + (1.0 - alpha) * dn[k-1];
      rsiArr[k] = (dn[k] > 1e-12) ? (100.0 - 100.0 / (1.0 + up[k] / dn[k])) : 100.0;
     }

//--- current spread in points
   double spreadNow = (double)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spreadNow <= 0.0)
      spreadNow = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point;

   if(m.Rows() != SEQ || m.Cols() != NFEAT)
      m.Resize(SEQ, NFEAT);

   int f0 = n - SEQ;                       // first bar of the model window
   for(int k = 0; k < SEQ; k++)
     {
      int i = f0 + k;                      // index of the bar in the arrays above
      int f = 0;
@@FEATUREBLOCK@@
      if(f != NFEAT)
        {
         Print("feature count mismatch: ", f, " vs ", NFEAT);
         return(false);
        }
     }

//--- run the model
   vectorf out(1);
   if(!OnnxRun(g_onnx, ONNX_NO_CONVERSION, m, out))
     {
      Print("OnnxRun failed, error ", GetLastError());
      return(false);
     }
   prob = (double)out[0];
   return(true);
  }

//+------------------------------------------------------------------+
int OnInit()
  {
   uint flags = ONNX_LOGLEVEL_ERROR;
   if(InpCommonFolder)
      flags |= ONNX_COMMON_FOLDER;      // the tester agent cannot see the terminal MQL5\Files, but it sees Common\Files
   g_onnx = OnnxCreate(InpOnnxFile, flags);
   if(g_onnx == INVALID_HANDLE)
     {
      Print("OnnxCreate failed for ", InpOnnxFile, " : ", GetLastError());
      return(INIT_FAILED);
     }
   const long inShape[]  = {1, SEQ, NFEAT};
   const long outShape[] = {1};
   if(!OnnxSetInputShape(g_onnx, 0, inShape))
     {
      Print("OnnxSetInputShape failed: ", GetLastError());
      return(INIT_FAILED);
     }
   if(!OnnxSetOutputShape(g_onnx, 0, outShape))
     {
      Print("OnnxSetOutputShape failed: ", GetLastError());
      return(INIT_FAILED);
     }

   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(20);
   g_trade.SetTypeFillingBySymbol(_Symbol);

   PrintFormat("ONNX ready: %s | seq=%d feats=%d | thr=%.2f | hold=%d bars",
               InpOnnxFile, SEQ, NFEAT, InpThreshold, InpHoldBars);
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(g_onnx != INVALID_HANDLE)
      OnnxRelease(g_onnx);
   PrintFormat("predictions=%I64u buys=%I64u sells=%I64u", g_preds, g_bought, g_sold);
  }

//+------------------------------------------------------------------+
void OnTick()
  {
   datetime barTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(barTime == 0)
      return;
   if(barTime == g_lastBar)
      return;                             // work once per bar
   g_lastBar = barTime;

//--- time based exit
   if(HasPosition())
     {
      if(g_entryBar > 0 && (barTime - g_entryBar) / PeriodSeconds(PERIOD_CURRENT) >= InpHoldBars)
         ClosePosition("horizon reached");
      else
         return;                          // stay in the position
     }

//--- spread filter
   double spreadNow = (double)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(InpMaxSpread > 0 && spreadNow > InpMaxSpread)
     {
      if(InpVerbose)
         PrintFormat("skip bar: spread %.0f > %d points", spreadNow, InpMaxSpread);
      return;
     }

//--- prediction
   matrixf m(SEQ, NFEAT);
   double prob = 0.0;
   if(!BuildFeatures(m, prob))
      return;
   g_preds++;
   if(InpVerbose)
      PrintFormat("prediction #%I64u  prob=%.4f  (thr %.2f/%.2f)", g_preds, prob, InpThreshold, 1.0 - InpThreshold);

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double sl, tp;

   if(prob >= InpThreshold)
     {
      sl = (InpSLPoints > 0) ? ask - InpSLPoints * _Point : 0.0;
      tp = (InpTPPoints > 0) ? ask + InpTPPoints * _Point : 0.0;
      if(g_trade.Buy(InpLot, _Symbol, 0.0, sl, tp, "hermes-onnx"))
        {
         g_bought++;
         g_entryBar = barTime;
        }
      else
         Print("Buy failed: ", g_trade.ResultRetcode(), " ", g_trade.ResultComment());
     }
   else if(prob <= 1.0 - InpThreshold)
     {
      sl = (InpSLPoints > 0) ? bid + InpSLPoints * _Point : 0.0;
      tp = (InpTPPoints > 0) ? bid - InpTPPoints * _Point : 0.0;
      if(g_trade.Sell(InpLot, _Symbol, 0.0, sl, tp, "hermes-onnx"))
        {
         g_sold++;
         g_entryBar = barTime;
        }
      else
         Print("Sell failed: ", g_trade.ResultRetcode(), " ", g_trade.ResultComment());
     }
  }
//+------------------------------------------------------------------+
'''


def make(meta_path):
    with open(meta_path, encoding="utf-8") as f:
        meta = json.load(f)
    feats = meta["feats"]
    base = os.path.basename(meta_path)
    for suffix in (".meta.json", ".json"):
        if base.endswith(suffix):
            base = base[:-len(suffix)]
            break

    missing = [f for f in feats if f not in EXPR]
    if missing:
        print("нет выражения для признаков:", missing)
        return None

    lines = []
    for idx, name in enumerate(feats):
        lines.append("      m[k][%2d] = (float)(%s); f++;" % (idx, EXPR[name]))
    block = "\n".join(lines)

    src = (TEMPLATE
           .replace("@@FEATUREBLOCK@@", block)
           .replace("@@NAME@@", base + ".mq5")
           .replace("@@MODEL@@", base)
           .replace("@@SEQ@@", str(meta["seq"]))
           .replace("@@NFEAT@@", str(len(feats)))
           .replace("@@HORIZON@@", str(meta["horizon"]))
           .replace("@@MAGIC@@", str(20260928)))

    out = os.path.join(EXPERTS, base + ".mq5")
    with open(out, "w", encoding="ascii") as f:
        f.write(src)
    print("советник создан:", out, "(признаков %d, окно %d, горизонт %d)" % (len(feats), meta["seq"], meta["horizon"]))
    return out


made = []
for mp in sorted(glob.glob(os.path.join(MODELS_ONNX, "*.meta.json"))):
    p = make(mp)
    if p:
        made.append(p)
print("создано советников:", len(made))
print("EA DONE")
